spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://yudai-mysql.mysql.database.azure.com:3306/defaultdb"
    username: yudai
    password: Uyupota@
  # データベースのスキーマ
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts
  sql:
    init:
      mode: always
      schema-locations: classpath:azuredatabaseschema.sql # Taskテーブル作成用クエリ
  # session:
  #   store-type: redis
